# This is a syncAllNenoToNotion workflow 

name: sync all neno to notion

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 
  syncAllNenoToNotion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: check
        run: | 
          curl --location --request GET 'https://api.github.com/repos/Mran/neno/contents/syncAllNenoToNotion.js' \
          --header 'pragma: no-cache' \
          --header 'accept: application/vnd.github.v3.raw+json' \
          --header 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36'\
          > syncAllNenoToNotion.js
          
   
      
      - run: pwd
      - run: ls
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      
      - name: install dependence
        run: npm i node-fetch@2.6.6
      
      - name: runSync
        env:
          NOTION_DATABASEID: 00bbe01eeb8e4741aaa7f80a1ae07e4e
          NOTION_TOKEN: secret_NOCpmWKvEQ79w548hCqbPyNuyxf4NItQcotzXx7BcO2
          GITHUB_TOKEN: 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
        run: node syncAllNenoToNotion.js
        
       
 